version: "3.11"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django-k8spam:v1
    command: ./migrate.sh
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  mysql_db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
    ports:
      - "3307:3306"
    
volumes:
  mysql_data: