name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Remove old Docker images
      run: docker system prune -a --force
    
    - name: Build the Docker image
      run: | 
          docker-compose build mysql_db 
          docker-compose build spam-docker-image 
          docker images
    
    - name: Push to Docker hub
      run: |
        docker push cyberbhavin/mysql_db
        docker push cyberbhavin/spam-docker-image:latest
      
