name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Remove old Docker images
      run: docker system prune -a --force
    
    - name: Build the Docker image
      run: | 
          docker-compose build spam-docker-image 
          docker images
    
    - name: Tag the Docker image
      run: docker tag spam-docker-image docker.io/cyberbhavin/spam-docker-image:latest

    - name: Push to Docker hub
      run: docker push cyberbhavin/spam-docker-image:latest
      
  deploy:
    needs: build
    runs-on: ip-172-31-5-47
    steps:
      - name: Pull image from dockerhub
        run: |
          docker pull mysql:8
          docker pull cyberbhavin/spam-docker-image:latest
      - name: Delete Old and Run new Container
        run: |
          docker-compose down --force
          docker-compose up 