name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Remove old Docker images
      run: docker system prune -a --force
    
    - name: Build the Docker image
      run: | 
          docker-compose build spam-docker-image 
          docker-compose build spam-mysql-db
          docker images
    
    - name: Tag the Docker image
      run: |
        docker tag spam-docker-image docker.io/cyberbhavin/spam-docker-image:latest
        docker tag spam-mysql-db docker.io/cyberbhavin/spam-mysql-db:latest

    - name: Push to Docker hub
      run: |
        docker push cyberbhavin/spam-docker-image:latest
        docker push cyberbhavin/spam-mysql-db:latest
      
  deploy:
    needs: build
    runs-on: self-hosted
    
    steps:     
      - name: Pull image from dockerhub
        run: |
          docker pull cyberbhavin/spam-docker-image:latest
          docker pull cyberbhavin/spam-mysql-db:latest
          docker images
      - name: Delete Old Container
        run: |
          docker rm -f spam-docker-image
          docker rm -f spam-mysql-db
          docker images
      - name: Remove old Docker images
        run: |
          docker images --filter dangling=true -q | xargs -r docker rmi
          docker images
      - name: Run new Container
        run: |
          docker run -d -p 3307:3306 --name spam-mysql-db -v mysql_data:/var/lib/mysql/ -e MYSQL_ROOT_PASSWORD={{secrets.MYSQL_ROOT_PASSWORD}}
          docker run -d -p 8000:8000 --name spam-docker-image --link spam-mysql-db:external-mysql cyberbhavin/spam-docker-image:latest