name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@15.206.167.144 << EOF
            cd /path/to/your/project
            docker-compose down
            # docker-compose pull
            docker-compose up -d
