name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t your-image-name .
        docker tag your-image-name:latest your-repo-uri/your-image-name:latest
        echo ${{ secrets.AWS_ECR_PASSWORD }} | docker login -u AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}
        docker push your-repo-uri/your-image-name:latest

    - name: Deploy to EC2 (SSH)
      uses: appleboy/ssh-action@v0.3.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker-compose -f docker-compose.yml up -d
